@extends('layouts.base')
@section('body')
<div class="jumbotron">
	<h1>References</h1>
	<p>For all Alu, L1 and SVA insertions</p>
</div>
@include('nav')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-10 col-md-offset-1 center">
			<br>
			<ol>
				<LI><b>Study ID</b>:1985-01; Economou-Pachnis A, Tsichlis PN. Insertion of an Alu SINE in the human homologue of the Mlvi-2 locus. Nucleic Acids Res. 1985 Dec 9;13(23):8379-87.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=3001638">PMID:3001638</a></LI><br>
				<LI><b>Study ID</b>:1988-01; Kazazian HH Jr, Wong C, Youssoufian H, Scott AF, Phillips DG, Antonarakis SE. Haemophilia A resulting from de novo insertion of L1 sequences represents a novelmechanism for mutation in man. Nature. 1988 Mar 10;332(6160):164-6.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=2831458">PMID:2831458</a></LI><br>
				<LI><b>Study ID</b>:1990-01; Stoppa-Lyonnet D, Carter PE, Meo T, Tosi M. Clusters of intragenic Alu repeats predispose the human C1 inhibitor locus todeleterious rearrangements. Proc Natl Acad Sci U S A. 1990 Feb;87(4):1551-5.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=2154751">PMID:2154751</a></LI><br>
				<LI><b>Study ID</b>:1991-01; Muratani K, Hada T, Yamamoto Y, Kaneko T, Shigeto Y, Ohue T, Furuyama J,Higashino K. Inactivation of the cholinesterase gene by Alu insertion: possible mechanism for human gene transposition. Proc Natl Acad Sci U S A. 1991 Dec 15;88(24):11315-9.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=1662391">PMID:1662391</a></LI><br>
				<LI><b>Study ID</b>:1991-02; Wallace MR, Andersen LB, Saulino AM, Gregory PE, Glover TW, Collins FS. A de novo Alu insertion results in neurofibromatosis type 1. Nature. 1991 Oct 31;353(6347):864-6.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=1719426">PMID:1719426</a></LI><br>
				<LI><b>Study ID</b>:1992-01; Miki Y, Nishisho I, Horii A, Miyoshi Y, Utsunomiya J, Kinzler KW, Vogelstein B,Nakamura Y. Disruption of the APC gene by a retrotransposal insertion of L1 sequence in acolon cancer. Cancer Res. 1992 Feb 1;52(3):643-5.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=1310068">PMID:1310068</a></LI><br>
				<LI><b>Study ID</b>:1993-01; Vidaud D, Vidaud M, Bahnak BR, Siguret V, Gispert Sanchez S, Laurian Y, Meyer D, Goossens M, Lavergne JM. Haemophilia B due to a de novo insertion of a human-specific Alu subfamily memberwithin the coding region of the factor IX gene. Eur J Hum Genet. 1993;1(1):30-6.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=8069649">PMID:8069649</a></LI><br>
				<LI><b>Study ID</b>:1993-02; Goldberg YP, Rommens JM, Andrew SE, Hutchinson GB, Lin B, Theilmann J, Graham R, Glaves ML, Starr E, McDonald H, et al. Identification of an Alu retrotransposition event in close proximity to a strong candidate gene for Huntington's disease. Nature. 1993 Mar 25;362(6418):370-3.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=8384324">PMID:8384324</a></LI><br>
				<LI><b>Study ID</b>:1993-03; Narita N, Nishio H, Kitoh Y, Ishikawa Y, Ishikawa Y, Minami R, Nakamura H, MatsuoM. Insertion of a 5' truncated L1 element into the 3' end of exon 44 of thedystrophin gene resulted in skipping of the exon during splicing in a case ofDuchenne muscular dystrophy. J Clin Invest. 1993 May;91(5):1862-7.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=8387534">PMID:8387534</a></LI><br>
				<LI><b>Study ID</b>:1994-01; Tassabehji M, Strachan T, Anderson M, Campbell RD, Collier S, Lako M. Identification of a novel family of human endogenous retroviruses andcharacterization of one family member, HERV-K(C4), located in the complement C4gene cluster. Nucleic Acids Res. 1994 Dec 11;22(24):5211-7.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=7816608">PMID:7816608</a></LI><br>
				<LI><b>Study ID</b>:1994-02; Holmes SE, Dombroski BA, Krebs CM, Boehm CD, Kazazian HH Jr. A new retrotransposable human L1 element from the LRE2 locus on chromosome 1qproduces a chimaeric insertion. Nat Genet. 1994 Jun;7(2):143-8.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=7920631">PMID:7920631</a></LI><br>
				<LI><b>Study ID</b>:1994-03; Hassoun H, Coetzer TL, Vassiliadis JN, Sahr KE, Maalouf GJ, Saad ST, Catanzariti L, Palek J. A novel mobile element inserted in the alpha spectrin gene: spectrin dayton. Atruncated alpha spectrin associated with hereditary elliptocytosis. J Clin Invest. 1994 Aug;94(2):643-8.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=8040317">PMID:8040317</a></LI><br>
				<LI><b>Study ID</b>:1995-01; Batzer MA, Rubin CM, Hellmann-Blumberg U, Alegria-Hartman M, Leeflang EP, SternJD, Bazan HA, Shaikh TH, Deininger PL, Schmid CW. Dispersion and insertion polymorphism in two small subfamilies of recentlyamplified human Alu repeats. J Mol Biol. 1995 Mar 31;247(3):418-27.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=7714898">PMID:7714898</a></LI><br>
				<LI><b>Study ID</b>:1995-02; Janicic N, Pausova Z, Cole DE, Hendy GN. Insertion of an Alu sequence in the Ca(2+)-sensing receptor gene in familialhypocalciuric hypercalcemia and neonatal severe hyperparathyroidism. Am J Hum Genet. 1995 Apr;56(4):880-6.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=7717399">PMID:7717399</a></LI><br>
				<LI><b>Study ID</b>:1996-01; Batzer MA, Arcot SS, Phinney JW, Alegria-Hartman M, Kass DH, Milligan SM, KimptonC, Gill P, Hochmeister M, Ioannou PA, Herrera RJ, Boudreau DA, Scheer WD, KeatsBJ, Deininger PL, Stoneking M. Genetic variation of recent Alu insertions in human populations. J Mol Evol. 1996 Jan;42(1):22-9.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=8576959">PMID:8576959</a></LI><br>
				<LI><b>Study ID</b>:1996-02; Miki Y, Katagiri T, Kasumi F, Yoshimoto T, Nakamura Y. Mutation analysis in the BRCA2 gene in primary breast cancers. Nat Genet. 1996 Jun;13(2):245-7.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=8640237">PMID:8640237</a></LI><br>
				<LI><b>Study ID</b>:1997-01; Arcot SS, DeAngelis MM, Sherry ST, Adamson AW, Lamerdin JE, Deininger PL, CarranoAV, Batzer MA. Identification and characterization of two polymorphic Ya5 Alu repeats. Mutat Res. 1997 Sep;382(1-2):5-11.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=9360633">PMID:9360633</a></LI><br>
				<LI><b>Study ID</b>:1997-02; Abdelhak S, Kalatzis V, Heilig R, Compain S, Samson D, Vincent C, Levi-Acobas F, Cruaud C, Le Merrer M, Mathieu M, König R, Vigneron J, Weissenbach J, Petit C,Weil D. Clustering of mutations responsible for branchio-oto-renal (BOR) syndrome in the eyes absent homologous region (eyaHR) of EYA1. Hum Mol Genet. 1997 Dec;6(13):2247-55.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=9361030">PMID:9361030</a></LI><br>
				<LI><b>Study ID</b>:1998-01; Yoshida K, Nakamura A, Yazaki M, Ikeda S, Takeda S. Insertional mutation by transposable element, L1, in the DMD gene results inX-linked dilated cardiomyopathy. Hum Mol Genet. 1998 Jul;7(7):1129-32.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=9618170">PMID:9618170</a></LI><br>
				<LI><b>Study ID</b>:1998-02; Kobayashi K, Nakahori Y, Miyake M, Matsumura K, Kondo-Iida E, Nomura Y, Segawa M,Yoshioka M, Saito K, Osawa M, Hamano K, Sakakihara Y, Nonaka I, Nakagome Y,Kanazawa I, Nakamura Y, Tokunaga K, Toda T. An ancient retrotransposal insertion causes Fukuyama-type congenital musculardystrophy. Nature. 1998 Jul 23;394(6691):388-92.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=9690476">PMID:9690476</a></LI><br>
				<LI><b>Study ID</b>:1998-03; Schwahn U, Lenzner S, Dong J, Feil S, Hinzmann B, van Duijnhoven G, Kirschner R, Hemberger M, Bergen AA, Rosenberg T, Pinckers AJ, Fundele R, Rosenthal A, CremersFP, Ropers HH, Berger W. Positional cloning of the gene for X-linked retinitis pigmentosa 2. Nat Genet. 1998 Aug;19(4):327-32.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=9697692">PMID:9697692</a></LI><br>
				<LI><b>Study ID</b>:1998-04; Arcot SS, Adamson AW, Risch GW, LaFleur J, Robichaux MB, Lamerdin JE, Carrano AV,Batzer MA. High-resolution cartography of recently integrated human chromosome 19-specificAlu fossils. J Mol Biol. 1998 Sep 4;281(5):843-56.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=9719639">PMID:9719639</a></LI><br>
				<LI><b>Study ID</b>:1999-01; Rohrer J, Minegishi Y, Richter D, Eguiguren J, Conley ME. Unusual mutations in Btk: an insertion, a duplication, an inversion, and fourlarge deletions. Clin Immunol. 1999 Jan;90(1):28-37.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=9884350">PMID:9884350</a></LI><br>
				<LI><b>Study ID</b>:1999-02; Oldridge M, Zackai EH, McDonald-McGinn DM, Iseki S, Morriss-Kay GM, Twigg SR,Johnson D, Wall SA, Jiang W, Theda C, Jabs EW, Wilkie AO. De novo alu-element insertions in FGFR2 identify a distinct pathological basisfor Apert syndrome. Am J Hum Genet. 1999 Feb;64(2):446-61.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=9973282">PMID:9973282</a></LI><br>
				<LI><b>Study ID</b>:1999-03; Halling KC, Lazzaro CR, Honchel R, Bufill JA, Powell SM, Arndt CA, Lindor NM. Hereditary desmoid disease in a family with a germline Alu I repeat mutation ofthe APC gene. Hum Hered. 1999 Mar;49(2):97-102.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=10077730">PMID:10077730</a></LI><br>
				<LI><b>Study ID</b>:1999-04; Kimberland ML, Divoky V, Prchal J, Schwahn U, Berger W, Kazazian HH Jr. Full-length human L1 insertions retain the capacity for high frequencyretrotransposition in cultured cells. Hum Mol Genet. 1999 Aug;8(8):1557-60.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=10401005">PMID:10401005</a></LI><br>
				<LI><b>Study ID</b>:1999-05; Mustajoki S, Ahola H, Mustajoki P, Kauppinen R. Insertion of Alu element responsible for acute intermittent porphyria. Hum Mutat. 1999;13(6):431-8.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=10408772">PMID:10408772</a></LI><br>
				<LI><b>Study ID</b>:1999-06; den Hollander AI, ten Brink JB, de Kok YJ, van Soest S, van den Born LI, vanDriel MA, van de Pol DJ, Payne AM, Bhattacharya SS, Kellner U, Hoyng CB,Westerveld A, Brunner HG, Bleeker-Wagemakers EM, Deutman AF, Heckenlively JR,Cremers FP, Bergen AA. Mutations in a human homologue of Drosophila crumbs cause retinitis pigmentosa(RP12). Nat Genet. 1999 Oct;23(2):217-21.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=10508521">PMID:10508521</a></LI><br>
				<LI><b>Study ID</b>:1999-07; Kondo-Iida E, Kobayashi K, Watanabe M, Sasaki J, Kumagai T, Koide H, Saito K,Osawa M, Nakamura Y, Toda T. Novel mutations and genotype-phenotype relationships in 107 families withFukuyama-type congenital muscular dystrophy (FCMD). Hum Mol Genet. 1999 Nov;8(12):2303-9.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=10545611">PMID:10545611</a></LI><br>
				<LI><b>Study ID</b>:2000-01; Zhang Y, Dipple KM, Vilain E, Huang BL, Finlayson G, Therrell BL, Worley K,Deininger P, McCabe ER. AluY insertion (IVS4-52ins316alu) in the glycerol kinase gene from an individual with benign glycerol kinase deficiency. Hum Mutat. 2000;15(4):316-23.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=10737976">PMID:10737976</a></LI><br>
				<LI><b>Study ID</b>:2000-02; Boissinot S, Chevret P, Furano AV. L1 (LINE-1) retrotransposon evolution and amplification in recent human history. Mol Biol Evol. 2000 Jun;17(6):915-28.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=10833198">PMID:10833198</a></LI><br>
				<LI><b>Study ID</b>:2000-03; Meischl C, Boer M, Ahlin A, Roos D. A new exon created by intronic insertion of a rearranged LINE-1 element as thecause of chronic granulomatous disease. Eur J Hum Genet. 2000 Sep;8(9):697-703.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=10980575">PMID:10980575</a></LI><br>
				<LI><b>Study ID</b>:2000-04; Su LK, Steinbach G, Sawyer JC, Hindi M, Ward PA, Lynch PM. Genomic rearrangements of the APC tumor-suppressor gene in familial adenomatouspolyposis. Hum Genet. 2000 Jan;106(1):101-7.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=10982189">PMID:10982189</a></LI><br>
				<LI><b>Study ID</b>:2000-05; Roy AM, Carroll ML, Nguyen SV, Salem AH, Oldridge M, Wilkie AO, Batzer MA,Deininger PL. Potential gene conversion and source genes for recently integrated Alu elements. Genome Res. 2000 Oct;10(10):1485-95.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=11042148">PMID:11042148</a></LI><br>
				<LI><b>Study ID</b>:2000-06; Sheen FM, Sherry ST, Risch GM, Robichaux M, Nasidze I, Stoneking M, Batzer MA,Swergold GD. Reading between the LINEs: human genomic variation induced by LINE-1retrotransposition. Genome Res. 2000 Oct;10(10):1496-508.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=11042149">PMID:11042149</a></LI><br>
				<LI><b>Study ID</b>:2001-01; Watkins WS, Ricker CE, Bamshad MJ, Carroll ML, Nguyen SV, Batzer MA, HarpendingHC, Rogers AR, Jorde LB. Patterns of ancestral human diversity: an analysis of Alu-insertion andrestriction-site polymorphisms. Am J Hum Genet. 2001 Mar;68(3):738-52. Epub 2001 Feb 15.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=11179020">PMID:11179020</a></LI><br>
				<LI><b>Study ID</b>:2001-02; Li X, Scaringe WA, Hill KA, Roberts S, Mengos A, Careri D, Pinto MT, Kasper CK,Sommer SS. Frequency of recent retrotransposition events in the human factor IX gene. Hum Mutat. 2001 Jun;17(6):511-9.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=11385709">PMID:11385709</a></LI><br>
				<LI><b>Study ID</b>:2001-03; Carroll ML, Roy-Engel AM, Nguyen SV, Salem AH, Vogel E, Vincent B, Myers J, AhmadZ, Nguyen L, Sammarco M, Watkins WS, Henke J, Makalowski W, Jorde LB, DeiningerPL, Batzer MA. Large-scale analysis of the Alu Ya5 and Yb8 subfamilies and their contribution tohuman genomic diversity. J Mol Biol. 2001 Aug 3;311(1):17-40.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=11469855">PMID:11469855</a></LI><br>
				<LI><b>Study ID</b>:2001-04; Kulski JK, Martinez P, Longman-Jacobsen N, Wang W, Williamson J, Dawkins RL,Shiina T, Naruse T, Inoko H. The association between HLA-A alleles and an Alu dimorphism near HLA-G. J Mol Evol. 2001 Aug;53(2):114-23.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=11479682">PMID:11479682</a></LI><br>
				<LI><b>Study ID</b>:2001-05; Roy-Engel AM, Carroll ML, Vogel E, Garber RK, Nguyen SV, Salem AH, Batzer MA,Deininger PL. Alu insertion polymorphisms for the study of human genomic diversity. Genetics. 2001 Sep;159(1):279-90.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=11560904">PMID:11560904</a></LI><br>
				<LI><b>Study ID</b>:2001-06; Turner G, Barbulescu M, Su M, Jensen-Seaman MI, Kidd KK, Lenz J. Insertional polymorphisms of full-length endogenous retroviruses in humans. Curr Biol. 2001 Oct 2;11(19):1531-5.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=11591322">PMID:11591322</a></LI><br>
				<LI><b>Study ID</b>:2001-07; Ostertag EM, Kazazian HH Jr. Biology of mammalian L1 retrotransposons. Annu Rev Genet. 2001;35:501-38.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=11700292">PMID:11700292</a></LI><br>
				<LI><b>Study ID</b>:2001-08; Sukarova E, Dimovski AJ, Tchacarova P, Petkov GH, Efremov GD. An Alu insert as the cause of a severe form of hemophilia A. Acta Haematol. 2001;106(3):126-9.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=11713379">PMID:11713379</a></LI><br>
				<LI><b>Study ID</b>:2001-09; Ovchinnikov I, Troxel AB, Swergold GD. Genomic characterization of recent human LINE-1 insertions: evidence supportingrandom insertion. Genome Res. 2001 Dec;11(12):2050-8.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=11731495">PMID:11731495</a></LI><br>
				<LI><b>Study ID</b>:2002-01; Kulski JK, Dunn DS, Hui J, Martinez P, Romphruk AV, Leelayuwat C, Tay GK, Oka A, Inoko H. Alu polymorphism within the MICB gene and association with HLA-B alleles. Immunogenetics. 2002 Feb;53(10-11):975-9. Epub 2002 Jan 26.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=11862397">PMID:11862397</a></LI><br>
				<LI><b>Study ID</b>:2002-02; Kutsche K, Ressler B, Katzera HG, Orth U, Gillessen-Kaesbach G, Morlot S,Schwinger E, Gal A. Characterization of breakpoint sequences of five rearrangements in L1CAM andABCD1 (ALD) genes. Hum Mutat. 2002 May;19(5):526-35.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=11968085">PMID:11968085</a></LI><br>
				<LI><b>Study ID</b>:2002-03; Myers JS, Vincent BJ, Udall H, Watkins WS, Morrish TA, Kilroy GE, Swergold GD,Henke J, Henke L, Moran JV, Jorde LB, Batzer MA. A comprehensive analysis of recently integrated human Ta L1 elements. Am J Hum Genet. 2002 Aug;71(2):312-26. Epub 2002 Jun 17.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=12070800">PMID:12070800</a></LI><br>
				<LI><b>Study ID</b>:2002-04; Brouha B, Meischl C, Ostertag E, de Boer M, Zhang Y, Neijens H, Roos D, Kazazian HH Jr. Evidence consistent with human L1 retrotransposition in maternal meiosis I. Am J Hum Genet. 2002 Aug;71(2):327-36. Epub 2002 Jul 1.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=12094329">PMID:12094329</a></LI><br>
				<LI><b>Study ID</b>:2002-05; Mamedov I, Batrak A, Buzdin A, Arzumanyan E, Lebedev Y, Sverdlov ED. Genome-wide comparison of differences in the integration sites of interspersedrepeats between closely related genomes. Nucleic Acids Res. 2002 Jul 15;30(14):e71.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=12136119">PMID:12136119</a></LI><br>
				<LI><b>Study ID</b>:2002-06; Tighe PJ, Stevens SE, Dempsey S, Le Deist F, Rieux-Laucat F, Edgar JD. Inactivation of the Fas gene by Alu insertion: retrotransposition in an introncausing splicing variation and autoimmune lymphoproliferative syndrome. Genes Immun. 2002 Oct;3 Suppl 1:S66-70.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=12215906">PMID:12215906</a></LI><br>
				<LI><b>Study ID</b>:2002-07; Dunn DS, Naruse T, Inoko H, Kulski JK. The association between HLA-A alleles and young Alu dimorphisms near the HLA-J,-H, and -F genes in workshop cell lines and Japanese and Australian populations. J Mol Evol. 2002 Dec;55(6):718-26.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=12486530">PMID:12486530</a></LI><br>
				<LI><b>Study ID</b>:2003-01; Salem AH, Myers JS, Otieno AC, Watkins WS, Jorde LB, Batzer MA. LINE-1 preTa elements in the human genome. J Mol Biol. 2003 Feb 28;326(4):1127-46.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=12589758">PMID:12589758</a></LI><br>
				<LI><b>Study ID</b>:2003-02; Buzdin A, Ustyugova S, Gogvadze E, Lebedev Y, Hunsmann G, Sverdlov E. Genome-wide targeted search for human specific and polymorphic L1 integrations. Hum Genet. 2003 May;112(5-6):527-33. Epub 2003 Feb 25.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=12601470">PMID:12601470</a></LI><br>
				<LI><b>Study ID</b>:2003-03; Badge RM, Alisch RS, Moran JV. ATLAS: a system to selectively identify human-specific L1 insertions. Am J Hum Genet. 2003 Apr;72(4):823-38. Epub 2003 Mar 11.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=12632328">PMID:12632328</a></LI><br>
				<LI><b>Study ID</b>:2003-04; Brouha B, Schustak J, Badge RM, Lutz-Prigge S, Farley AH, Moran JV, Kazazian HHJr. Hot L1s account for the bulk of retrotransposition in the human population. Proc Natl Acad Sci U S A. 2003 Apr 29;100(9):5280-5. Epub 2003 Apr 7.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=12682288">PMID:12682288</a></LI><br>
				<LI><b>Study ID</b>:2003-05; Salem AH, Kilroy GE, Watkins WS, Jorde LB, Batzer MA. Recently integrated Alu elements and human genomic diversity. Mol Biol Evol. 2003 Aug;20(8):1349-61. Epub 2003 May 30.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=12777511">PMID:12777511</a></LI><br>
				<LI><b>Study ID</b>:2003-06; van den Hurk JA, van de Pol DJ, Wissinger B, van Driel MA, Hoefsloot LH, de Wijs IJ, van den Born LI, Heckenlively JR, Brunner HG, Zrenner E, Ropers HH, CremersFP. Novel types of mutation in the choroideremia ( CHM) gene: a full-length L1insertion and an intronic mutation activating a cryptic exon. Hum Genet. 2003 Aug;113(3):268-75. Epub 2003 Jun 25.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=12827496">PMID:12827496</a></LI><br>
				<LI><b>Study ID</b>:2003-07; Ganguly A, Dunbar T, Chen P, Godmilow L, Ganguly T. Exon skipping caused by an intronic insertion of a young Alu Yb9 element leads tosevere hemophilia A. Hum Genet. 2003 Sep;113(4):348-52. Epub 2003 Jul 12.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=12884004">PMID:12884004</a></LI><br>
				<LI><b>Study ID</b>:2003-08; Dunn DS, Inoko H, Kulski JK. Dimorphic Alu element located between the TFIIH and CDSN genes within the majorhistocompatibility complex. Electrophoresis. 2003 Aug;24(16):2740-8.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=12929169">PMID:12929169</a></LI><br>
				<LI><b>Study ID</b>:2003-09; Claverie-Martin F, González-Acosta H, Flores C, Antón-Gamero M, García-Nieto V. De novo insertion of an Alu sequence in the coding region of the CLCN5 generesults in Dent's disease. Hum Genet. 2003 Nov;113(6):480-5. Epub 2003 Aug 29.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=14569459">PMID:14569459</a></LI><br>
				<LI><b>Study ID</b>:2003-10; Callinan PA, Hedges DJ, Salem AH, Xing J, Walker JA, Garber RK, Watkins WS,Bamshad MJ, Jorde LB, Batzer MA. Comprehensive analysis of Alu-associated diversity on the human sex chromosomes. Gene. 2003 Oct 23;317(1-2):103-10.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=14604797">PMID:14604797</a></LI><br>
				<LI><b>Study ID</b>:2003-11; Martínez-Garay I, Ballesta MJ, Oltra S, Orellana C, Palomeque A, Moltó MD, PrietoF, Martínez F. Intronic L1 insertion and F268S, novel mutations in RPS6KA3 (RSK2) causingCoffin-Lowry syndrome. Clin Genet. 2003 Dec;64(6):491-6.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=14986828">PMID:14986828</a></LI><br>
				<LI><b>Study ID</b>:2003-12; Xing J, Salem AH, Hedges DJ, Kilroy GE, Watkins WS, Schienman JE, Stewart CB,Jurka J, Jorde LB, Batzer MA. Comprehensive analysis of two Alu Yd subfamilies. J Mol Evol. 2003;57 Suppl 1:S76-89.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=15008405">PMID:15008405</a></LI><br>
				<LI><b>Study ID</b>:2004-01; Hughes JF, Coffin JM. Human endogenous retrovirus K solo-LTR formation and insertional polymorphisms:implications for human and viral evolution. Proc Natl Acad Sci U S A. 2004 Feb 10;101(6):1668-72. Epub 2004 Feb 2.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=14757818">PMID:14757818</a></LI><br>
				<LI><b>Study ID</b>:2004-02; Mukherjee S, Mukhopadhyay A, Banerjee D, Chandak GR, Ray K. Molecular pathology of haemophilia B: identification of five novel mutationsincluding a LINE 1 insertion in Indian patients. Haemophilia. 2004 May;10(3):259-63.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=15086324">PMID:15086324</a></LI><br>
				<LI><b>Study ID</b>:2004-03; Ishihara N, Yamada K, Yamada Y, Miura K, Kato J, Kuwabara N, Hara Y, Kobayashi Y,Hoshino K, Nomura Y, Mimaki M, Ohya K, Matsushima M, Nitta H, Tanaka K, Segawa M,Ohki T, Ezoe T, Kumagai T, Onuma A, Kuroda T, Yoneda M, Yamanaka T, Saeki M,Segawa M, Saji T, Nagaya M, Wakamatsu N. Clinical and molecular analysis of Mowat-Wilson syndrome associated with ZFHX1Bmutations and deletions at 2q22-q24.1. J Med Genet. 2004 May;41(5):387-93.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=15121779">PMID:15121779</a></LI><br>
				<LI><b>Study ID</b>:2004-04; Boissinot S, Entezam A, Young L, Munson PJ, Furano AV. The insertional history of an active family of L1 retrotransposons in humans. Genome Res. 2004 Jul;14(7):1221-31. Epub 2004 Jun 14.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=15197167">PMID:15197167</a></LI><br>
				<LI><b>Study ID</b>:2004-05; Otieno AC, Carter AB, Hedges DJ, Walker JA, Ray DA, Garber RK, Anders BA,Stoilova N, Laborde ME, Fowlkes JD, Huang CH, Perodeau B, Batzer MA. Analysis of the human Alu Ya-lineage. J Mol Biol. 2004 Sep 3;342(1):109-18.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=15313610">PMID:15313610</a></LI><br>
				<LI><b>Study ID</b>:2004-06; Mamedov I, Lebedev Y, Hunsmann G, Khusnutdinova E, Sverdlov E. A rare event of insertion polymorphism of a HERV-K LTR in the human genome. Genomics. 2004 Sep;84(3):596-9.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=15498467">PMID:15498467</a></LI><br>
				<LI><b>Study ID</b>:2004-07; Bennett EA, Coleman LE, Tsui C, Pittard WS, Devine SE. Natural genetic variation caused by transposable elements in humans. Genetics. 2004 Oct;168(2):933-51.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=15514065">PMID:15514065</a></LI><br>
				<LI><b>Study ID</b>:2004-08; Carter AB, Salem AH, Hedges DJ, Keegan CN, Kimball B, Walker JA, Watkins WS,Jorde LB, Batzer MA. Genome-wide analysis of the human Alu Yb-lineage. Hum Genomics. 2004 Mar;1(3):167-78.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=15588477">PMID:15588477</a></LI><br>
				<LI><b>Study ID</b>:2005-01; Dunn DS, Tait BD, Kulski JK. The distribution of polymorphic Alu insertions within the MHC class I HLA-B7 and HLA-B57 haplotypes. Immunogenetics. 2005 Jan;56(10):765-8. Epub 2004 Dec 8.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=15592666">PMID:15592666</a></LI><br>
				<LI><b>Study ID</b>:2005-02; Mamedov IZ, Arzumanyan ES, Amosova AL, Lebedev YB, Sverdlov ED. Whole-genome experimental identification of insertion/deletion polymorphisms ofinterspersed repeats by a new general approach. Nucleic Acids Res. 2005 Jan 26;33(2):e16.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=15673711">PMID:15673711</a></LI><br>
				<LI><b>Study ID</b>:2005-03; Salem AH, Ray DA, Hedges DJ, Jurka J, Batzer MA. Analysis of the human Alu Ye lineage. BMC Evol Biol. 2005 Feb 22;5:18.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=15725352">PMID:15725352</a></LI><br>
				<LI><b>Study ID</b>:2005-04; Chen JM, Stenson PD, Cooper DN, Férec C. A systematic analysis of LINE-1 endonuclease-dependent retrotranspositionalevents causing human genetic disease. Hum Genet. 2005 Sep;117(5):411-27. Epub 2005 Jun 28.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=15983781">PMID:15983781</a></LI><br>
				<LI><b>Study ID</b>:2005-05; Dunn DS, Romphruk AV, Leelayuwat C, Bellgard M, Kulski JK. Polymorphic Alu insertions and their associations with MHC class I alleles andhaplotypes in the northeastern Thais. Ann Hum Genet. 2005 Jul;69(Pt 4):364-72.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=15996165">PMID:15996165</a></LI><br>
				<LI><b>Study ID</b>:2005-06; Teugels E, De Brakeleer S, Goelen G, Lissens W, Sermijn E, De Grève J. De novo Alu element insertions targeted to a sequence common to the BRCA1 andBRCA2 genes. Hum Mutat. 2005 Sep;26(3):284.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=16088935">PMID:16088935</a></LI><br>
				<LI><b>Study ID</b>:2005-07; Garber RK, Hedges DJ, Herke SW, Hazard NW, Batzer MA. The Alu Yc1 subfamily: sorting the wheat from the chaff. Cytogenet Genome Res. 2005;110(1-4):537-42.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=16093706">PMID:16093706</a></LI><br>
				<LI><b>Study ID</b>:2005-08; Ray DA, Walker JA, Hall A, Llewellyn B, Ballantyne J, Christian AT, Turteltaub K,Batzer MA. Inference of human geographic origins using Alu insertion polymorphisms. Forensic Sci Int. 2005 Oct 29;153(2-3):117-24.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=16139099">PMID:16139099</a></LI><br>
				<LI><b>Study ID</b>:2005-09; Belshaw R, Dawson AL, Woolven-Allen J, Redding J, Burt A, Tristem M. Genomewide screening reveals high levels of insertional polymorphism in the humanendogenous retrovirus family HERV-K(HML2): implications for present-day activity. J Virol. 2005 Oct;79(19):12507-14.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=16160178">PMID:16160178</a></LI><br>
				<LI><b>Study ID</b>:2005-10; Wang H, Xing J, Grover D, Hedges DJ, Han K, Walker JA, Batzer MA. SVA elements: a hominid-specific retroposon family. J Mol Biol. 2005 Dec 9;354(4):994-1007. Epub 2005 Oct 19.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=16288912">PMID:16288912</a></LI><br>
				<LI><b>Study ID</b>:2006-01; Wang J, Song L, Gonder MK, Azrak S, Ray DA, Batzer MA, Tishkoff SA, Liang P. Whole genome computational comparative genomics: A fruitful approach forascertaining Alu insertion polymorphisms. Gene. 2006 Jan 3;365:11-20. Epub 2006 Jan 10.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=16376498">PMID:16376498</a></LI><br>
				<LI><b>Study ID</b>:2007-01; Konkel MK, Wang J, Liang P, Batzer MA. Identification and characterization of novel polymorphic LINE-1 insertionsthrough comparison of two human genome sequence assemblies. Gene. 2007 Apr 1;390(1-2):28-38. Epub 2006 Aug 30.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=17034961">PMID:17034961</a></LI><br>
				<LI><b>Study ID</b>:2007-02; Levy S, Sutton G, Ng PC, Feuk L, Halpern AL, Walenz BP, Axelrod N, Huang J,Kirkness EF, Denisov G, Lin Y, MacDonald JR, Pang AW, Shago M, Stockwell TB,Tsiamouri A, Bafna V, Bansal V, Kravitz SA, Busam DA, Beeson KY, McIntosh TC,Remington KA, Abril JF, Gill J, Borman J, Rogers YH, Frazier ME, Scherer SW,Strausberg RL, Venter JC. The diploid genome sequence of an individual human. PLoS Biol. 2007 Sep 4;5(10):e254.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=17803354">PMID:17803354</a></LI><br>
				<LI><b>Study ID</b>:2009-01; Xing J, Zhang Y, Han K, Salem AH, Sen SK, Huff CD, Zhou Q, Kirkness EF, Levy S,Batzer MA, Jorde LB. Mobile elements create structural variation: analysis of a complete human genome. Genome Res. 2009 Sep;19(9):1516-26. doi: 10.1101/gr.091827.109. Epub 2009 May 13.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=19439515">PMID:19439515</a></LI><br>
				<LI><b>Study ID</b>:2010-01; Gallus GN, Cardaioli E, Rufa A, Da Pozzo P, Bianchi S, D'Eramo C, Collura M,Tumino M, Pavone L, Federico A. Alu-element insertion in an OPA1 intron sequence associated with autosomaldominant optic atrophy. Mol Vis. 2010 Feb 10;16:178-83.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=20157369">PMID:20157369</a></LI><br>
				<LI><b>Study ID</b>:2010-02; Witherspoon DJ, Xing J, Zhang Y, Watkins WS, Batzer MA, Jorde LB. Mobile element scanning (ME-Scan) by targeted high-throughput sequencing. BMC Genomics. 2010 Jun 30;11:410. doi: 10.1186/1471-2164-11-410.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=20591181">PMID:20591181</a></LI><br>
				<LI><b>Study ID</b>:2010-03; Kidd JM, Graves T, Newman TL, Fulton R, Hayden HS, Malig M, Kallicki J, Kaul R,Wilson RK, Eichler EE. A human genome structural variation sequencing resource reveals insights intomutational mechanisms. Cell. 2010 Nov 24;143(5):837-47. doi: 10.1016/j.cell.2010.10.027.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=21111241">PMID:21111241</a></LI><br>
				<LI><b>Study ID</b>:2011-01; Stewart C, Kural D, Strömberg MP, Walker JA, Konkel MK, Stütz AM, Urban AE,Grubert F, Lam HY, Lee WP, Busby M, Indap AR, Garrison E, Huff C, Xing J, Snyder MP, Jorde LB, Batzer MA, Korbel JO, Marth GT; 1000 Genomes Project. A comprehensive map of mobile element insertion polymorphisms in humans. PLoS Genet. 2011 Aug;7(8):e1002236. doi: 10.1371/journal.pgen.1002236. Epub 2011 Aug 18.
					<a target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=pubmed&dopt=Abstract&list_uids=21876680">PMID:21876680</a></LI><br>
				<LI><b>Study ID</b>:2013-01; Witherspoon DJ, Zhang Y, Xing J, Watkins WS, Ha H, Batzer MA, Jorde LB. Mobile element scanning (ME-Scan) identifies thousands of novel Alu insertions indiverse human populations. Genome Res. 2013 Jun 6;23(7):1170-81. doi: 10.1101/gr.148973.112. Epub 2013 Apr 18.
					<a  target="_blank" class="btn btn-success btn-xs" href="http://www.ncbi.nlm.nih.gov/pubmed/?term=Witherspoon+DJ%2C+Zhang+Y%2C+Xing+J%2C+Watkins+WS%2C+Ha+H%2C+Batzer+MA%2C+Jorde+LB">PMID:23599355</a></LI>
		</div>
	</div>
	<br><br>
</div>
@stop